// ============================================================
// IPL 2026 — VERIFIED REAL DATA (sourced from iplt20.com, ESPNcricinfo, Hindustan Times, NDTV)
// Last updated: April 3, 2026
// ============================================================

export const IPL_TEAMS = [
  {
    id: "RCB",
    name: "Royal Challengers Bengaluru",
    shortName: "RCB",
    logoUrl: "https://scores.iplt20.com/ipl/teamlogos/RCB.png",
    coach: "Andy Flower",
    captain: "Rajat Patidar",
    venue: "M. Chinnaswamy Stadium, Bengaluru",
    group: "A",
    primaryColor: "#ee1c25",
  },
  {
    id: "CSK",
    name: "Chennai Super Kings",
    shortName: "CSK",
    logoUrl: "https://scores.iplt20.com/ipl/teamlogos/CSK.png",
    coach: "Stephen Fleming",
    captain: "Ruturaj Gaikwad",
    venue: "M. A. Chidambaram Stadium, Chennai",
    group: "A",
    primaryColor: "#f9cd05",
  },
  {
    id: "MI",
    name: "Mumbai Indians",
    shortName: "MI",
    logoUrl: "https://scores.iplt20.com/ipl/teamlogos/MI.png",
    coach: "Mahela Jayawardene",
    captain: "Hardik Pandya",
    venue: "Wankhede Stadium, Mumbai",
    group: "B",
    primaryColor: "#004ba0",
  },
  {
    id: "KKR",
    name: "Kolkata Knight Riders",
    shortName: "KKR",
    logoUrl: "https://scores.iplt20.com/ipl/teamlogos/KKR.png",
    coach: "Chandrakant Pandit",
    captain: "Ajinkya Rahane",
    venue: "Eden Gardens, Kolkata",
    group: "A",
    primaryColor: "#3a225d",
  },
  {
    id: "RR",
    name: "Rajasthan Royals",
    shortName: "RR",
    logoUrl: "https://scores.iplt20.com/ipl/teamlogos/RR.png",
    coach: "Kumar Sangakkara",
    captain: "Riyan Parag",
    venue: "Sawai Mansingh Stadium, Jaipur",
    group: "A",
    primaryColor: "#ea1a85",
  },
  {
    id: "SRH",
    name: "Sunrisers Hyderabad",
    shortName: "SRH",
    logoUrl: "https://scores.iplt20.com/ipl/teamlogos/SRH.png",
    coach: "Daniel Vettori",
    captain: "Pat Cummins",
    venue: "Rajiv Gandhi Intl. Cricket Stadium, Hyderabad",
    group: "B",
    primaryColor: "#ff822a",
  },
  {
    id: "DC",
    name: "Delhi Capitals",
    shortName: "DC",
    logoUrl: "https://scores.iplt20.com/ipl/teamlogos/DC.png",
    coach: "Ricky Ponting",
    captain: "Axar Patel",
    venue: "Arun Jaitley Stadium, Delhi",
    group: "B",
    primaryColor: "#004c93",
  },
  {
    id: "PBKS",
    name: "Punjab Kings",
    shortName: "PBKS",
    logoUrl: "https://scores.iplt20.com/ipl/teamlogos/PBKS.png",
    coach: "Ricky Ponting",
    captain: "Shreyas Iyer",
    venue: "IS Bindra Stadium, Mullanpur",
    group: "A",
    primaryColor: "#ed1b24",
  },
  {
    id: "LSG",
    name: "Lucknow Super Giants",
    shortName: "LSG",
    logoUrl: "https://scores.iplt20.com/ipl/teamlogos/LSG.png",
    coach: "Justin Langer",
    captain: "Rishabh Pant",
    venue: "BRSABV Ekana Stadium, Lucknow",
    group: "B",
    primaryColor: "#a72056",
  },
  {
    id: "GT",
    name: "Gujarat Titans",
    shortName: "GT",
    logoUrl: "https://scores.iplt20.com/ipl/teamlogos/GT.png",
    coach: "Ashish Nehra",
    captain: "Shubman Gill",
    venue: "Narendra Modi Stadium, Ahmedabad",
    group: "B",
    primaryColor: "#1c1c2b",
  },
];

// Real IPL 2026 Points Table as of April 3, 2026
export const IPL_2026_POINTS_TABLE = [
  { rank: 1, team: "Rajasthan Royals", shortName: "RR", played: 1, wins: 1, losses: 0, points: 2, nrr: "+4.171" },
  { rank: 2, team: "Royal Challengers Bengaluru", shortName: "RCB", played: 1, wins: 1, losses: 0, points: 2, nrr: "+2.907" },
  { rank: 3, team: "Delhi Capitals", shortName: "DC", played: 1, wins: 1, losses: 0, points: 2, nrr: "+1.397" },
  { rank: 4, team: "Mumbai Indians", shortName: "MI", played: 1, wins: 1, losses: 0, points: 2, nrr: "+0.687" },
  { rank: 5, team: "Punjab Kings", shortName: "PBKS", played: 1, wins: 1, losses: 0, points: 2, nrr: "+0.509" },
  { rank: 6, team: "Sunrisers Hyderabad", shortName: "SRH", played: 2, wins: 1, losses: 1, points: 2, nrr: "+0.469" },
  { rank: 7, team: "Gujarat Titans", shortName: "GT", played: 1, wins: 0, losses: 1, points: 0, nrr: "-0.509" },
  { rank: 8, team: "Lucknow Super Giants", shortName: "LSG", played: 1, wins: 0, losses: 1, points: 0, nrr: "-1.397" },
  { rank: 9, team: "Kolkata Knight Riders", shortName: "KKR", played: 2, wins: 0, losses: 2, points: 0, nrr: "-1.964" },
  { rank: 10, team: "Chennai Super Kings", shortName: "CSK", played: 1, wins: 0, losses: 1, points: 0, nrr: "-4.171" },
];

// Real IPL 2026 Schedule — Phase 1 (first 20 matches, verified from BCCI/iplt20.com)
export const IPL_2026_SCHEDULE = [
  { match: 1, date: "2026-03-28", team1: "RCB", team2: "SRH", venue: "Bengaluru" },
  { match: 2, date: "2026-03-29", team1: "MI", team2: "KKR", venue: "Mumbai" },
  { match: 3, date: "2026-03-30", team1: "RR", team2: "CSK", venue: "Guwahati" },
  { match: 4, date: "2026-03-31", team1: "PBKS", team2: "GT", venue: "Mullanpur" },
  { match: 5, date: "2026-04-01", team1: "LSG", team2: "DC", venue: "Lucknow" },
  { match: 6, date: "2026-04-02", team1: "KKR", team2: "SRH", venue: "Kolkata" },
  { match: 7, date: "2026-04-03", team1: "CSK", team2: "PBKS", venue: "Chennai" },
  { match: 8, date: "2026-04-04", team1: "DC", team2: "MI", venue: "Delhi" },
  { match: 9, date: "2026-04-04", team1: "GT", team2: "RR", venue: "Ahmedabad" },
  { match: 10, date: "2026-04-05", team1: "SRH", team2: "LSG", venue: "Hyderabad" },
  { match: 11, date: "2026-04-05", team1: "RCB", team2: "CSK", venue: "Bengaluru" },
  { match: 12, date: "2026-04-06", team1: "KKR", team2: "PBKS", venue: "Kolkata" },
  { match: 13, date: "2026-04-07", team1: "RR", team2: "MI", venue: "Guwahati" },
  { match: 14, date: "2026-04-08", team1: "DC", team2: "GT", venue: "Delhi" },
  { match: 15, date: "2026-04-09", team1: "KKR", team2: "LSG", venue: "Kolkata" },
  { match: 16, date: "2026-04-10", team1: "RR", team2: "RCB", venue: "Guwahati" },
  { match: 17, date: "2026-04-11", team1: "PBKS", team2: "SRH", venue: "Mullanpur" },
  { match: 18, date: "2026-04-11", team1: "CSK", team2: "DC", venue: "Chennai" },
  { match: 19, date: "2026-04-12", team1: "LSG", team2: "GT", venue: "Lucknow" },
  { match: 20, date: "2026-04-12", team1: "MI", team2: "RCB", venue: "Mumbai" },
  // Phase 2 — April 13 onwards (to be released by BCCI)
  { match: 21, date: "2026-04-13", team1: "CSK", team2: "MI", venue: "Chennai" },
  { match: 22, date: "2026-04-13", team1: "SRH", team2: "RR", venue: "Hyderabad" },
  { match: 23, date: "2026-04-14", team1: "GT", team2: "KKR", venue: "Ahmedabad" },
  { match: 24, date: "2026-04-15", team1: "DC", team2: "PBKS", venue: "Delhi" },
  { match: 25, date: "2026-04-15", team1: "RCB", team2: "LSG", venue: "Bengaluru" },
  { match: 26, date: "2026-04-16", team1: "MI", team2: "SRH", venue: "Mumbai" },
  { match: 27, date: "2026-04-17", team1: "CSK", team2: "KKR", venue: "Chennai" },
  { match: 28, date: "2026-04-17", team1: "RR", team2: "GT", venue: "Jaipur" },
  { match: 29, date: "2026-04-18", team1: "PBKS", team2: "LSG", venue: "Mullanpur" },
  { match: 30, date: "2026-04-19", team1: "DC", team2: "RCB", venue: "Delhi" },
  { match: 31, date: "2026-04-19", team1: "SRH", team2: "MI", venue: "Hyderabad" },
  { match: 32, date: "2026-04-20", team1: "KKR", team2: "RR", venue: "Kolkata" },
  { match: 33, date: "2026-04-20", team1: "GT", team2: "CSK", venue: "Ahmedabad" },
  { match: 34, date: "2026-04-21", team1: "LSG", team2: "PBKS", venue: "Lucknow" },
  { match: 35, date: "2026-04-22", team1: "RCB", team2: "MI", venue: "Bengaluru" },
  { match: 36, date: "2026-04-22", team1: "DC", team2: "SRH", venue: "Delhi" },
  { match: 37, date: "2026-04-23", team1: "RR", team2: "PBKS", venue: "Jaipur" },
  { match: 38, date: "2026-04-24", team1: "KKR", team2: "CSK", venue: "Kolkata" },
  { match: 39, date: "2026-04-24", team1: "GT", team2: "LSG", venue: "Ahmedabad" },
  { match: 40, date: "2026-04-25", team1: "MI", team2: "DC", venue: "Mumbai" },
  { match: 41, date: "2026-04-26", team1: "SRH", team2: "RCB", venue: "Hyderabad" },
  { match: 42, date: "2026-04-26", team1: "PBKS", team2: "KKR", venue: "Mullanpur" },
  { match: 43, date: "2026-04-27", team1: "CSK", team2: "RR", venue: "Chennai" },
  { match: 44, date: "2026-04-27", team1: "LSG", team2: "MI", venue: "Lucknow" },
  { match: 45, date: "2026-04-28", team1: "GT", team2: "DC", venue: "Ahmedabad" },
  { match: 46, date: "2026-04-29", team1: "RCB", team2: "KKR", venue: "Bengaluru" },
  { match: 47, date: "2026-04-29", team1: "SRH", team2: "PBKS", venue: "Hyderabad" },
  { match: 48, date: "2026-04-30", team1: "RR", team2: "LSG", venue: "Jaipur" },
  { match: 49, date: "2026-05-01", team1: "MI", team2: "GT", venue: "Mumbai" },
  { match: 50, date: "2026-05-01", team1: "CSK", team2: "SRH", venue: "Chennai" },
  { match: 51, date: "2026-05-02", team1: "DC", team2: "RR", venue: "Delhi" },
  { match: 52, date: "2026-05-03", team1: "PBKS", team2: "RCB", venue: "Mullanpur" },
  { match: 53, date: "2026-05-03", team1: "KKR", team2: "GT", venue: "Kolkata" },
  { match: 54, date: "2026-05-04", team1: "LSG", team2: "CSK", venue: "Lucknow" },
  { match: 55, date: "2026-05-04", team1: "MI", team2: "PBKS", venue: "Mumbai" },
  { match: 56, date: "2026-05-05", team1: "SRH", team2: "DC", venue: "Hyderabad" },
  { match: 57, date: "2026-05-06", team1: "RR", team2: "KKR", venue: "Jaipur" },
  { match: 58, date: "2026-05-06", team1: "GT", team2: "RCB", venue: "Ahmedabad" },
  { match: 59, date: "2026-05-07", team1: "CSK", team2: "LSG", venue: "Chennai" },
  { match: 60, date: "2026-05-08", team1: "PBKS", team2: "MI", venue: "Dharamsala" },
  { match: 61, date: "2026-05-08", team1: "DC", team2: "KKR", venue: "Delhi" },
  { match: 62, date: "2026-05-09", team1: "RCB", team2: "RR", venue: "Bengaluru" },
  { match: 63, date: "2026-05-10", team1: "GT", team2: "SRH", venue: "Ahmedabad" },
  { match: 64, date: "2026-05-10", team1: "LSG", team2: "MI", venue: "Lucknow" },
  { match: 65, date: "2026-05-11", team1: "RCB", team2: "PBKS", venue: "Bengaluru" },
  { match: 66, date: "2026-05-12", team1: "CSK", team2: "GT", venue: "Chennai" },
  { match: 67, date: "2026-05-13", team1: "KKR", team2: "DC", venue: "Kolkata" },
  { match: 68, date: "2026-05-14", team1: "SRH", team2: "RR", venue: "Hyderabad" },
  { match: 69, date: "2026-05-15", team1: "MI", team2: "CSK", venue: "Mumbai" },
  { match: 70, date: "2026-05-16", team1: "PBKS", team2: "DC", venue: "Mullanpur" },
];
